### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by godalming123**
Improve readme with capital letters links to pages when it mentions them and piont out that this is a suckless WM so no compositer, bar or keybinder.

### CODE REVIEW

**Comment by flyingcakes85** [comment]
suckless?

**Comment by codic12** [comment]
Yeah, while it's somewhat similar to dwm in philosophy it has no relation to suckless, can you remove that part?

**Comment by godalming123** [comment]
removed suckles from readme sorry didnt realise it was a whole organisation thought it was just a software mentality

**Comment by codic12** [comment]
appreciated, ty!

**Pull request merged**
